"""initial migration

Revision ID: 59366427c04f
Revises:
Create Date: 2026-05-01 12:13:52.816706

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "59366427c04f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("BACKLOG", "PLAYING", "COMPLETED", "DROPPED", name="gamestatus"),
            nullable=False,
        ),
        sa.Column(
            "platform",
            sa.Enum("STEAM", "EPIC", "GOG", "OTHER", name="gameplatform"),
            nullable=False,
        ),
        sa.Column("hours_played", sa.Integer(), nullable=False),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("game")
    # ### end Alembic commands ###
